COMEX/urls.py
from django.urls import path
from . import views
from . import forms

# Registrar el espacio de nombres de esta aplicacion
app_name = 'COMEX'
# Lista con los patrones URL de la aplicacion...
urlpatterns = [
    # Reglas para las paginas de la aplicacion
]

Construimport/urls.py
from django import urls, views
import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.urls.conf import include
import notifications.urls
from Dashboard.models import Dashboard
from Dashboard import urls
from Salvas import urls
from Solicitudes.views import *


urlpatterns = [
    path('admin/', RedirectView.as_view(url='/admin/Dashboard/dashboard' , permanent=False)),
    path('admin/Salvas/', include('Salvas.urls', namespace='Salvas')),
    path('admin/Reportes/', include('Reportes.urls')),
    path('admin/Solicitudes/', include('Solicitudes.urls')),
    path('admin/Nomencladores/', include('Nomencladores.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    #path('admin_tools_stats/', include('admin_tools_stats.urls')),
    #path('pdf/', include('django_pdf.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Salvas/urls.py
# Copyright (c) 2009 Guilherme Semente and contributors
#
# This file is part of Django Smuggler.
#
# Django Smuggler is free software under terms of the GNU Lesser
# General Public License version 3 (LGPLv3) as published by the Free
# Software Foundation. See the file README for copying conditions.

from django.urls import include, path, reverse_lazy, re_path

from .views import *

DB_SAVE =reverse_lazy('db_save',)

DB_RESTORE = reverse_lazy( 'db_restore',)

app_name = 'Salvas'

urlpatterns = [
    
    path('salvas/backups/', display, name='Salvas'),
    
    path('db_save/', db_save, name='salvar'),
   
    path('db_restore/<name>', db_restore, name='restaurar'),
    
    path('eliminar/<name>', remove_file, name='eliminar')
    
]

Salvas/models.py
from django.db import models

# Create your models here.
class Salvas(models.Model):
    proxy = True
    
    class Meta:
        verbose_name = ('Salva y Restaura')
        verbose_name_plural = ('Salvas y Restauras')

Salvas/views.py
from asyncio.windows_events import NULL
#from curses.ascii import NULL
from django.shortcuts import redirect, render

# Create your views here.
# Copyright (c) 2009 Guilherme Semente and contributors
#
# This file is part of Django Smuggler.
#
# Django Smuggler is free software under terms of the GNU Lesser
# General Public License version 3 (LGPLv3) as published by the Free
# Software Foundation. See the file README for copying conditions.
from audioop import add
from multiprocessing import context
import os.path
import subprocess
import tempfile
from django.conf import settings
from datetime import datetime
import mimetypes
from django.contrib import messages
from django.contrib.admin.helpers import AdminForm
from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.management.base import CommandError
from django.core.serializers.base import DeserializationError
from django.db import IntegrityError
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.encoding import force_str
from django.utils.translation import gettext_lazy as _
from django.utils.translation import ngettext_lazy
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import admin
import time
#from cryptography.fernet import Fernet
import wget
from django.urls import reverse_lazy


# from smuggler import settings
# from smuggler.forms import ImportForm
# from smuggler.utils import (
#     load_fixtures,
#     save_uploaded_file_on_disk,
#     serialize_to_response,
# )
 

def save_address_dbs(address):
    # fich = open("static/db/dblist.txt")
    # lines = fich.readlines() 
    # address = address + '\n'
    # fich.close() 
    # if address not in lines:
    #     if lines.__len__() == 0:
    #         lines.append(address)
    #     #elif lines.__len__() == 4:
    #     #    for line in lines([3][0:-1]):
    #     #        lines.remove(line)
    #     elif lines.__len__() > 0 or lines.__len__() < 5:
    #         first = lines[0:]
    #         second = lines[1:]
    #         third = lines[2:]
    #         lines.clear()
    #         lines.append(address)
    #         lines.append(first)
    #         lines.append(second)
    #         lines.append(third)
    fich = open("static/db/dblist.txt", "a")
    print(address)
    fich.write(address + '\n')
    # for line in lines:
    #     fich.writelines(line)
    fich.close()
    
    
def list_address_db():
    fich = open("static/db/dblist.txt")
    lines = fich.readlines()
    fich.close()
    res = []
    print(lines)
    if lines.__len__()>0:
        for line in lines:
            print(line[:-2])
            line = line[:-1]
            fich = line.split("/")[2:]
            date = line.split(":")[0:]
            Year = date[0:3]
            Month = date[4:5]
            Day = date[6:7]
            Hour = date[8:9]
            Minute = date[10:11]
            Seconds = date[12:13]
            res.append([fich,Year,Month,Day,Hour,Minute, Seconds])
    res.reverse()
    return res

def remove_address_dbs(name):
    fich = open("static/db/dblist.txt")
    lines = fich.readlines() 
    fich.close() 
    index = 0
    address = 'static/db/' + name + '\n'
    
    lines.remove(address)
    
    with open("static/db/dblist.txt", "w") as fich:
        for nline in lines:
            fich.writelines(nline)
        
      
    # fich = open("static/db/dblist.txt", "w")
    # for nline in lines:
    #     fich.writelines(nline)
    # fich.close()    
            


def display(request):
    list = list_address_db()
    return render(request, 'salvarestaura.html', {'dblist': list})


@permission_required('auth.add_user', login_url='403')
def db_save(request):
    list = list_address_db()
    fecha_hora = str(datetime.today().strftime("%Y%m%d%H%M%S"))
    address = "static/db/" + fecha_hora + "construimport.sql" 
    PASSWORD = '3693'                ##CONTRASEÑA DE LA BD##
    os.putenv('PGPASSWORD', PASSWORD)
    address = "static/db/" + fecha_hora + "construimport.sql"   ##RUTA DONDE SE GUARDA EL ARCHIVO DE LA BD##
    try:
        subprocess.Popen("pg_dump -c -h localhost -p 5432 -U postgres -d construimport > " + address, shell=True)
        time.sleep(1)
        save_address_dbs(address)
        list = list_address_db()
        messages.success(request, "Datos salvados")
        return redirect('Salvas:Salvas')
        # return render(request, 'salvarestaura.html', {'dblist': list})
    except:        
        return render(request, 'salvarestaura.html', {'dblist': list})      
    #return render(request, 'salvarestaura.html', {'dblist': list})


@permission_required('auth.add_user', login_url='403')
def db_restore(request:HttpRequest, name):
    list = list_address_db()
    address = "static/db/" + name    ##RUTA DONDE ESTA GUARDADO EL ARCHIVO DE LA BD##
    PASSWORD = '3693'                ##CONTRASEÑA DE LA BD##
    os.putenv('PGPASSWORD', PASSWORD)
    restore_context = {
        'list' : list,
        'name' : name
    }
    try:
        subprocess.Popen("psql -h localhost -p 5432 -U postgres -d construimport <" + address, shell=True)
        messages.success(request, "Datos restaurados correctamente")
        return render(request, 'salvarestaura.html', {'dblist': list})
    except:
        messages.error(request, "Error al restaurar la base de datos")
        return render(request, 'salvarestaura.html', {'dblist': list}) 
   
@permission_required('auth.add_user', login_url='403')    
def remove_file(request:HttpResponse, name):
    list = list_address_db()
    print(request.META.get("REMOTE_ADDR"))
    remove_address_dbs(name)
    print(name)
    address = "static/db/" + name
    time.sleep(1)
    os.remove(address)
    return redirect('Salvas:Salvas')

Salvas/templates/salvarestaura.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify jazzmin %}
{% get_jazzmin_settings request as jazzmin_settings %}

{% block extrahead %}
    <link type="text/css" href="{% static 'jazzmin/vendor/notyf/notyf.min.css' %}" rel="stylesheet">
   
    <!-- Core -->
    <script src="{% static 'jazzmin/vendor/@popperjs/core/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'jazzmin/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>

    <!-- Vendor JS -->
    <script src="{% static 'jazzmin/vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>

    <!-- Slider -->

    <link type="text/css" href="{% static 'jazzmin/vendor/sweetalert2/dist/sweetalert2.min.css' %}" rel="stylesheet">
    <script src="{% static 'jazzmin/vendor/nouislider/distribute/nouislider.min.js' %}"></script>

    <!-- Smooth scroll -->
    <script src="{% static 'jazzmin/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>

    <!-- Charts -->
    <script src="{% static 'jazzmin/vendor/chartist/dist/chartist.min.js' %}"></script>
    <script src="{% static 'jazzmin/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js' %}"></script>

    <!-- Datepicker -->
    <script src="{% static 'jazzmin/vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

    <!-- Sweet Alerts 2 -->
    <script src="{% static 'jazzmin/vendor/sweetalert2/dist/sweetalert2.all.min.js' %}"></script>

    <!-- Moment JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

    <!-- Vanilla JS Datepicker -->
    <script src="{% static 'jazzmin/vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

    <!-- Notyf -->
    <script src="{% static 'jazzmin/vendor/notyf/notyf.min.js' %}"></script>

    <!-- Simplebar -->
    <script src="{% static 'jazzmin/vendor/simplebar/dist/simplebar.min.js' %}"></script>

    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

    <!-- Volt JS -->
    <script src="{% static 'jazzmin/js/volt/volt.js' %}"></script>
    <script src="{% static 'jazzmin/js/volt/scripts.js' %}"></script>
    <script src="https://kit.fontawesome.com/4fd3baa9fc.js" crossorigin="anonymous"></script>

{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block content_title %} {% trans 'Listado de Salvas y Restauras' %} {% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'admin:index' %}"><i class="fa fa-building-alt"></i> {% trans 'Home' %}</a></li>
        <li class="breadcrumb-item">{% trans 'Salvas y Restauras' %}</li>
    </ol>
{% endblock %}

{% block content %}

{% get_side_menu using="app_list" as dashboard_list %}
    {% if dashboard_list %}
    {% widthratio dashboard_list|length 2 1 as middle %}
    {% endif %}


<div class="wrapper">	
	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="card">
				<form class="form-horizontal" method="post" id="form" action="{% url 'Salvas:Salvas' %}">

						{% csrf_token %}
					<div class="card-header-primary">

						 	<div class="col-md-12 text-right">
							 	<button id="submit" type="submit" class="btn btn-success">
									<a href="{% url 'Salvas:salvar'%}">
								 	<span class="fa fa-save" style="color: #0e0f11;"> Salvar</span>
								 	</a>
								</button>
						 	</div>

					</div>
					<!-- /.card-header -->
					<div class="card-body">
						<div class="form-body">
							<table id="example2" class="table table-bordered table-hover table-responsive-sm">
								<thead>
								<tr>
									<th>
										Número
									</th>
									<th>
										Ruta de la salva
									</th>
									<th>
										Nombre del fichero
									</th>
									<th>
										Acción
									</th>
								</tr>
								</thead>
								<tbody>
								{% for u in dblist %}
									<tr>
										<td>
											{{ forloop.counter }}
										</td>
										<td>
											{{ u.1.0 }} 
										</td>
										<td>
											{{ u.0.0 }}
										</td>

										<td>
											<span class="input-group-sm">
											<a href="{% url 'Salvas:restaurar' u.0.0 %}"

										   	class="btn btn-sm btn-primary" tit	le="Restaurar base de datos">
												<i class="fa fa-history"></i>

											</a>
											{% if forloop.counter > 2 %}
												<a href="{% url 'Salvas:eliminar' u.0.0 %}" class="btn btn-danger btn-sm"
												title="Eliminar Archivo" >
												<i class="fa fa-eraser"></i>
												</a>
											{% endif %}
											</span>
										</td>
									</tr>
								{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				<!-- /.card-body -->
				</form>
				</div>
				<!-- /.card -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
	</section>
</div>	
{% endblock %}

{% block extrajs %}
    {{  block.super }}
    <script type="text/javascript" src="{% static 'vendor/select2/js/select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jazzmin/js/change_form.js' %}"></script>
    {% if jazzmin_settings.related_modal_active %}
    <script type="text/javascript" src="{% static 'jazzmin/plugins/bootstrap-show-modal/bootstrap-show-modal.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jazzmin/js/related-modal.js' %}"></script>
    {% endif %}
{% endblock %}