COMEX/urls.py
from django.urls import path
from . import views
from . import forms

# Registrar el espacio de nombres de esta aplicacion
app_name = 'COMEX'
# Lista con los patrones URL de la aplicacion...
urlpatterns = [
    # Reglas para las paginas de la aplicacion
]

Construimport/urls.py
from django import urls, views
import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.urls.conf import include
import notifications.urls
from Dashboard.models import Dashboard
from Dashboard import urls
from Salvas import urls
from Solicitudes.views import *


urlpatterns = [
    path('admin/', RedirectView.as_view(url='/admin/Dashboard/dashboard' , permanent=False)),
    path('admin/Salvas/', include('Salvas.urls', namespace='Salvas')),
    path('admin/Reportes/', include('Reportes.urls')),
    path('admin/Solicitudes/', include('Solicitudes.urls')),
    path('admin/Nomencladores/', include('Nomencladores.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    #path('admin_tools_stats/', include('admin_tools_stats.urls')),
    #path('pdf/', include('django_pdf.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Solicitudes/urls.py
from django.urls import include, path, reverse_lazy, re_path
from . import views
from django.views.generic import CreateView
from . import forms
from Solicitudes.views import *
# Registrar el espacio de nombres de esta aplicacion
app_name = 'Solicitudes'
# Lista con los patrones URL de la aplicacion...
urlpatterns = [
    path('<int:id>/generatePDF/', views.generatePDF, name='generatePDF'),
    #path('solicitud_equipo/add/', Solicitud_Equipo_FormView.as_view(), name='add'),
    path('solicitud_equipo/add/', Agregar_Solicitud_Equipo.as_view([FSolicitud_Equipo, FSolicitud_Equipo_Proxy, FSolicitud_Equipo_Confirmar]), name='solicitud_equipo'),
    path('solicitud_ppa/add/', Agregar_Solicitud_PPA.as_view([FSolicitud_PPA, FSolicitud_PPA_Proxy]), name='solicitud_ppa'),
    path('solicitud_neumatico/add/', Agregar_Solicitud_Neumatico.as_view([FSolicitud_Neumatico, FSolicitud_Neumatico_Proxy]), name='solicitud_neumatico'),
    path('solicitud_bateria/add/', Agregar_Solicitud_Bateria.as_view([FSolicitud_Bateria, FSolicitud_Bateria_Proxy]), name='solicitud_bateria'),
    
    # Reglas para las paginas de la aplicacion
]

Solicitudes/views.py
from ast import Eq
from multiprocessing import context
from re import template
from django.shortcuts import render
from django.views.generic.base import TemplateView
from formtools.wizard.views import WizardView, SessionWizardView
import io
from django.http import FileResponse
from pytest import Instance
from reportlab.pdfgen import canvas
from .models import *
from .forms import *
from django.views.generic import CreateView
from django.contrib import admin
from Solicitudes.admin import *
from django.forms.models import construct_instance
from django.db.models import base
#from Solicitudes.models import Solicitud
 
# Constuir solicitud       
#def salvar_solicitud(cliente, observaciones, valorestimado, producto, cantidad):
#    Solicitud_EquipoAdmin.save(cliente, observaciones, valorestimado, producto, cantidad)

class Agregar_Solicitud_Equipo(SessionWizardView):
    model = Solicitud_Equipo
    form_list = (('Datos Generales', FSolicitud_Equipo), 
                 ( 'Equipos', FSolicitud_Equipo_Proxy),
                 ('Confirmar', FSolicitud_Equipo_Confirmar)
                )
    #fields = ['numcontratocliente', 'observaciones', 'valor_estimado']
    template_name = 'solicitud_form.html'
    instance = None
    
    # def get_form(self, step=None, data=None, files=None):
    #     form = super().get_form(step, data, files)
    #     if step is None:
    #         step = self.steps.current
    #     if step == '2':
    #         data = self.get_cleaned_data_for_step('0')['cliente']
    #         form.fields['cliente'].label = data
    #     return form
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre_url'] = 'solicitud_equipo'
        context['opts'] = Solicitud_Equipo._meta,
        context['change'] = True,
        context['is_popup'] = False,
        context['save_as'] = False,
        context['has_delete_permission'] = False,
        context['has_add_permission'] = True,
        context['has_change_permission'] = False
        context['changeform_template'] = 'solicitud_form.html'
        context['nombre_formulario'] = 'Agregar Solicitud de Equipo'
        context['mensaje'] = 'La solicitud fue adicionada correctamente.'
        context.update(admin.site.each_context(self.request))
        print(self.steps.current)
        if self.steps.current == 2:
            context.update({2: self.get_all_cleaned_data()})
        if self.steps.current == 1:
            context.update({
                'FSolicitud_Equipo_Proxy': FSolicitud_Equipo_ProxyFormset()
            })
        return context
    
    def dispatch(self, request, *args, **kwargs):
        self.instance = Solicitud_Equipo()
        return super(Agregar_Solicitud_Equipo, self).dispatch(request, *args, **kwargs)
    
    def get_form_instance( self, step ):
        return self.instance 
    
   
    def done(self, form_list, **kwargs):
        # Crear la solicitud
           
        # Recorrer los productos
        # crear solicitud
        
        form_data = [form.cleaned_data for form in form_list]
                
        datos_sol = form_data[0]
        
        solicitud = Solicitud_Equipo()
        
        solicitud.cliente = datos_sol['cliente']
        solicitud.observaciones = datos_sol['observaciones']
        solicitud.valor_estimado = datos_sol['valor_estimado']
        solicitud.plazo = datos_sol['plazo']
        solicitud.fechasol = timezone.now()
        if solicitud.plazo == '3 días':
            delta1 = timezone.timedelta(days=3)
            solicitud.fecha_venc = solicitud.fechasol + delta1
            if solicitud.fecha_venc.weekday() == 5:
                solicitud.fecha_venc = solicitud.fecha_venc + timezone.timedelta(days=2)
            elif solicitud.fecha_venc.weekday() == 6:
                solicitud.fecha_venc = solicitud.fecha_venc + timezone.timedelta(days=1)    
        elif solicitud.plazo == '7 días':
            delta2 = timezone.timedelta(days=7)
            solicitud.fecha_venc = solicitud.fechasol + delta2
            if solicitud.fecha_venc.weekday() == 5:
                solicitud.fecha_venc = solicitud.fecha_venc + timezone.timedelta(days=2)
            elif solicitud.fecha_venc.weekday() == 6:
                solicitud.fecha_venc = solicitud.fecha_venc + timezone.timedelta(days=1) 
        solicitud.save()
                
        solicitud_proxy = form_data[1]
        
        l = list(solicitud_proxy.values())
        
        count = 0
        
        for equipo in Equipo.objects.filter(descripcion = l[0]):
            eproxy = Solicitud_Equipo_Proxy()
            eproxy.numsolicitud_id = solicitud.numsolicitud
            eproxy.idproducto_id = equipo.idproducto
            eproxy.cantidad = l[1]
            for p in Proveedor.objects.filter(equipos = eproxy.idproducto):
                print(p.activo)
                if p.activo == True:
                    eproveedor = Solicitud_Equipo_Proveedor()
                    eproveedor.numsolicitud_id = solicitud.numsolicitud
                    eproveedor.codmincex_id = p.codmincex
                    eproveedor.save()
                    count += 1
            eproxy.save()
        print(count)
        if count >= 2:
            messages.success(self.request,'Se agregó correctamente la Solicitud')
        else:
            solicitud.delete()
            messages.error(self.request, 'No hay suficientes proveedores para procesar la solicitud')
        return redirect('/admin/Solicitudes/solicitud_equipo/')  
        

    def form_valid(self, form):
        return super().form_valid(form)

class Agregar_Solicitud_PPA(SessionWizardView):
    model = Solicitud_PPA
    form_list = [FSolicitud_PPA, FSolicitud_PPA_Proxy]
    #fields = ['numcontratocliente', 'observaciones', 'valor_estimado']
    template_name = 'solicitud_form.html'
    instance = None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre_url'] = 'solicitud_ppa'
        context['opts'] = Solicitud_PPA._meta,
        context['change'] = True,
        context['is_popup'] = False,
        context['save_as'] = False,
        context['has_delete_permission'] = False,
        context['has_add_permission'] = True,
        context['has_change_permission'] = False
        context['changeform_template'] = 'solicitud_form.html'
        context['nombre_formulario'] = 'Agregar Solicitud de PPA'
        context['mensaje'] = 'La solicitud fue adicionada correctamente.'
        context.update(admin.site.each_context(self.request))
        return context
    
    def dispatch(self, request, *args, **kwargs):
        self.instance = Solicitud_PPA()
        return super(Agregar_Solicitud_PPA, self).dispatch(request, *args, **kwargs)
    
    def get_form_instance( self, step ):
        return self.instance 
    
   
    def done(self, form_list, **kwargs):
        # Crear la solicitud
           
        # Recorrer los productos
        # crear solicitud
        
        form_data = [form.cleaned_data for form in form_list]
                
        datos_sol = form_data[0]
        
        solicitud = Solicitud_PPA()
        
        solicitud.cliente = datos_sol['cliente']
        solicitud.observaciones = datos_sol['observaciones']
        solicitud.valor_estimado = datos_sol['valor_estimado']
        solicitud.plazo = datos_sol['plazo']
        solicitud.fechasol = timezone.now()
        if solicitud.plazo == '3 días':
            delta1 = timezone.timedelta(days=3)
            solicitud.fecha_venc = solicitud.fechasol + delta1
            if solicitud.fecha_venc.weekday() == 5:
                solicitud.fecha_venc = solicitud.fecha_venc + timezone.timedelta(days=2)
            elif solicitud.fecha_venc.weekday() == 6:
                solicitud.fecha_venc = solicitud.fecha_venc + timezone.timedelta(days=1)    
        elif solicitud.plazo == '7 días':
            delta2 = timezone.timedelta(days=7)
            solicitud.fecha_venc = solicitud.fechasol + delta2
            if solicitud.fecha_venc.weekday() == 5:
                solicitud.fecha_venc = solicitud.fecha_venc + timezone.timedelta(days=2)
            elif solicitud.fecha_venc.weekday() == 6:
                solicitud.fecha_venc = solicitud.fecha_venc + timezone.timedelta(days=1)         
        solicitud.save()
        
        print(solicitud)
        
        solicitud_proxy = form_data[1]
        
        l = list(solicitud_proxy.values())
        
        for ppa in PPA.objects.filter(descripcion = l[0]):
            ppaproxy = Solicitud_PPA_Proxy()
            ppaproxy.numsolicitud_id = solicitud.numsolicitud
            ppaproxy.idproducto_id= ppa.idproducto
            ppaproxy.cantidad = l[1]
            ppaproxy.save()
        
        return redirect('/admin/Solicitudes/solicitud_ppa/')  

    def form_valid(self, form):
        return super().form_valid(form)

class Agregar_Solicitud_Neumatico(SessionWizardView):
    model = Solicitud_Neumatico
    form_list = [FSolicitud_Neumatico, FSolicitud_Neumatico_Proxy]
    #fields = ['numcontratocliente', 'observaciones', 'valor_estimado']
    template_name = 'solicitud_form.html'
    instance = None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre_url'] = 'solicitud_neumatico'
        context['opts'] = Solicitud_Neumatico._meta,
        context['change'] = True,
        context['is_popup'] = False,
        context['save_as'] = False,
        context['has_delete_permission'] = False,
        context['has_add_permission'] = True,
        context['has_change_permission'] = False
        context['changeform_template'] = 'solicitud_form.html'
        context['nombre_formulario'] = 'Agregar Solicitud de Neumático'
        context['mensaje'] = 'La solicitud fue adicionada correctamente.'
        context.update(admin.site.each_context(self.request))
        return context
    
    

Solicitudes/templates/change_list_graph.html
{% extends "admin/change_list.html" %}
{% load static %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("idpais-chart");
            {% regroup cl.queryset|dictsort:"idpais" by get_idpais_display as idpais_list %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for idpais in idpais_list %}'{{ idpais.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for idpais in idpais_list %}'{{ idpais.list|length }}',{% endfor %}],
                        backgroundColor: [{% for idpais in idpais_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <h1>Gráfico </h1>
    <hr>
    <div class="col">
        <div class="col-sm-4">
            <canvas id="idpais-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

Solicitudes/templates/generate_pdf.html
{% extends "admin/change_form.html" %}

{% load i18n admin_urls %}

{% block object-tools-items %}
    <li>
        <a href="{% url 'Solicitudes:generatePDF' original.pk %}?next={% url 'admin:person_person_change' original.id %}" class="historylink">Generate PDF</a>
    </li>
    {% if has_absolute_url %}
        <li>
            <a href="{% url 'admin:view_on_site' content_type_id original.pk %}" class="viewsitelink">{% trans "View on site" %}</a>
        </li>
    {% endif %}
{% endblock %}

Solicitudes/templates/solicitud_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify jazzmin %}
{% get_jazzmin_settings request as jazzmin_settings %}

{% block extrastyle %} 
<style>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static "vendor/fontawesome-free/css/all.min.css" %}">

    <!-- Bootstrap and adminLTE -->
    <link rel="stylesheet" href="{% static "vendor/adminlte/css/adminlte.min.css" %}" id="adminlte-css">

    <!-- Bootswatch theme -->
    {% if jazzmin_ui.theme.name != 'default' %}
        <link rel="stylesheet" href="{{ jazzmin_ui.theme.src }}" id="jazzmin-theme" />
    {% endif %}

    {% if jazzmin_ui.dark_mode_theme %}
        <link rel="stylesheet" href="{{ jazzmin_ui.dark_mode_theme.src }}" id="jazzmin-dark-mode-theme" media="(prefers-color-scheme: dark)"/>
    {% endif %}

    <!-- Custom fixes for django -->
    <link rel="stylesheet" href="{% static "jazzmin/css/main.css" %}">

    {% if jazzmin_settings.custom_css %}
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static jazzmin_settings.custom_css %}">
    {% endif %}

    <!-- favicons -->
    <link rel="shortcut icon" href="{% static jazzmin_settings.site_icon %}" type="image/png">
    <link rel="icon" href="{% static jazzmin_settings.site_icon %}" sizes="32x32" type="image/png">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    
    {{ wizard.form.media }}

    
    <link rel="stylesheet" type="text/css" href="{% static "jazzmin/css/admin_extra.css" %}" />



/*custom font*/
    <script https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js></script>
/*basic reset*/
* {
    margin: 0;
    padding: 0;
}

html {
    height: 100%;
    background: transparent; /* fallback for old browsers */
    background: -webkit-linear-gradient(to left, #6441A5, #2a0845); /* Chrome 10-25, Safari 5.1-6 */
}

body {
    font-family: montserrat, arial, verdana;
    background-color: lightgray;
}

/*form styles*/
#msform {
    margin-left:370px;
    width:250%;
    align: center;
    text-align: center;
    position: relative;
    margin-top: 30px;
}

#msform fieldset {
    background: white;
    border: 0 none;
    border-radius: 0px;
    box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
    padding: 20px 30px;
    box-sizing: border-box;
    width: 80% ;
    margin: 0 10%;

    /*stacking fieldsets above each other*/
    position: relative;
}

/*Hide all except first fieldset*/
#msform fieldset:not(:first-of-type) {
    display: none;
}

/*inputs*/
#msform input, #msform textarea {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin-bottom: 10px;
    width: relative;
    box-sizing: border-box;
    font-family: arial;
    color: #2C3E50;
    font-size: 13px;
}

#msform input:focus, #msform textarea:focus {
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    border: 1px solid #ee0979;
    outline-width: 0;
    transition: All 0.5s ease-in;
    -webkit-transition: All 0.5s ease-in;
    -moz-transition: All 0.5s ease-in;
    -o-transition: All 0.5s ease-in;
}

/*buttons*/
#msform .action-button .submit {
    width: 100px;
    background: darkgoldenrod;
    font-weight: bold;
    color: white;
    border: 0 none;
    border-radius: 25px;
    cursor: pointer;
    padding: 10px 5px;
    margin: 10px 5px;
}

#msform .action-button:hover, #msform .action-button:focus .submit {
    box-shadow: 0 0 0 2px white, 0 0 0 3px darkgoldenrod;
}

#msform .action-button-previous .btn-primary .submit {
    width: 100px;
    background: gray;
    font-weight: bold;
    color: white;
    border: 0 none;
    border-radius: 25px;
    cursor: pointer;
    padding: 10px 5px;
    margin: 10px 5px;
}

#msform .action-button-previous:hover, #msform .action-button-previous:focus .btn-primary .submit {
    box-shadow: 0 0 0 2px white, 0 0 0 3px #C5C5F1;
}

/*headings*/
.fs-title {
    font-size: 18px;
    text-transform: uppercase;
    color: #2C3E50;
    margin-bottom: 10px;
    letter-spacing: 2px;
    font-weight: bold;
}

.fs-subtitle {
    font-weight: normal;
    font-size: 13px;
    color: #666;
    margin-bottom: 20px;
}

/*progressbar*/
#progressbar {
    margin-bottom: 30px;
    overflow: hidden;
    /*CSS counters to number the steps*/
    counter-reset: step;
}

#progressbar li {
    list-style-type: none;
    color: black;
    text-transform: uppercase;
    font-size: 9px;
    width: 32%;
    float: left;
    position: relative;
    letter-spacing: 1px;
}

#progressbar li:before {
    content: counter(step);
    counter-increment: step;
    width: 24px;
    height: 24px;
    line-height: 26px;
    display: block;
    font-size: 12px;
    color: #333;
    background: white;
    border-radius: 25px;
    margin: 0 auto 10px auto;
}

/*progressbar connectors*/
#progressbar li:after {
    content: '';
    width: 100%;
    height: 2px;
    background: white;
    position: absolute;
    left: -50%;
    top: 9px;
    z-index: -1; /*put it behind the numbers*/
}

#progressbar li:first-child:after {
    /*connector not needed before the first step*/
    content: none;
}

/*marking active/completed steps green*/
/*The number of the step and the connector before it = green*/
#progressbar li.active:before, #progressbar li.active:after {
    background: darkgoldenrod;
    color: black;
}


/* Not relevant to this form */
.dme_link {
    margin-top: 30px;
    text-align: center;
}
.dme_link a {
    background: #FFF;
    font-weight: bold;
    color: #ee0979;
    border: 0 none;
    border-radius: 25px;
    cursor: pointer;
    padding: 5px 25px;
    font-size: 12px;
}

.dme_link a:hover, .dme_link a:focus {
    background: #C5C5F1;
    text-decoration: none;
}
</style>
{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{% url 'admin:index' %}"><i class="fa fa-building-alt"></i> {% trans 'Home' %}</a></li>
        <li class="breadcrumb-item">{% trans 'Reportes' %}</li>
    </ol>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form id="msform" method="post" action="{{ form_url }}">
            {% csrf_token %}
            <!-- progressbar -->
            <ul id="progressbar">
                <h3>Paso {{ wizard.steps.step1 }} de {{ wizard.steps.count }}</h3>
            </ul>
            <!-- fieldsets -->
            <fieldset>
                <table>
                    <h3>Introduzca los Datos de la Solicitud</h3>
                    <div>
                        {{ wizard.management_form }}
                        {% if wizard.form.forms %}
                            {{ wizard.form.management_form }}
                            {% for form in wizard.form.forms %}
                                <br>
                                    {{ form.as_table }}
                                <br>
                            {% endfor %}
                        {% else %}
                            {{ wizard.form }}
                        {% endif %}
                    </div>
                </table>
                {% if wizard.steps.prev %}
                {% comment %} <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button> {% endcomment %}
                <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">Anterior</button>
                {% endif %}
                {% if wizard.steps.current == 2 %}
                    <h3>¿Está seguro de agregar la Siguiente Solicitud?</h3>
                {% endif %}
                {% comment %} <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.next }}">Siguiente</button> {% endcomment %}
                <input type="submit" value="Siguiente"/>
                {% comment %} {{ wizard.steps.current }} {% endcomment %}
            </fieldset>
        </form>
    </div>
</div>
{% block jquery %}
<script>
    //jQuery time
var current_fs, next_fs, previous_fs; //fieldsets
var left, opacity, scale; //fieldset properties which we will animate
var animating; //flag to prevent quick multi-click glitches

$(".next").click(function(){
	if(animating) return false;
	animating = true;
	
	current_fs = $(this).parent();
	next_fs = $(this).parent().next();
	
	//activate next step on progressbar using the index of next_fs
	$("#progressbar li").eq($("fieldset").index(next_fs)).addClass("active");
	
	//show the next fieldset
	next_fs.show(); 
	//hide the current fieldset with style
	current_fs.animate({opacity: 0}, {
		step: function(now, mx) {
			//as the opacity of current_fs reduces to 0 - stored in "now"
			//1. scale current_fs down to 80%
			scale = 1 - (1 - now) * 0.2;
			//2. bring next_fs from the right(50%)
			left = (now * 50)+"%";
			//3. increase opacity of next_fs to 1 as it moves in
			opacity = 1 - now;
			current_fs.css({
        'transform': 'scale('+scale+')',
        'position': 'absolute'
      });
			next_fs.css({'left': left, 'opacity': opacity});
		}, 
		duration: 800, 
		complete: function(){
			current_fs.hide();
			animating = false;
		}, 
		//this comes from the custom easing plugin
		easing: 'easeInOutBack'
	});
});

$(".previous").click(function(){
	if(animating) return false;
	animating = true;
	
	current_fs = $(this).parent();
	previous_fs = $(this).parent().prev();
	
	//de-activate current step on progressbar
	$("#progressbar li").eq($("fieldset").index(current_fs)).removeClass("active");
	
	//show the previous fieldset
	previous_fs.show(); 
	//hide the current fieldset with style
	current_fs.animate({opacity: 0}, {
		step: function(now, mx) {
			//as the opacity of current_fs reduces to 0 - stored in "now"
			//1. scale previous_fs from 80% to 100%
			scale = 0.8 + (1 - now) * 0.2;
			//2. take current_fs to the right(50%) - from 0%
			left = ((1-now) * 50)+"%";
			//3. increase opacity of previous_fs to 1 as it moves in
			opacity = 1 - now;
			current_fs.css({'left': left});
			previous_fs.css({'transform': 'scale('+scale+')', 'opacity': opacity});
		}, 
		duration: 800, 
		complete: function(){
			current_fs.hide();
			animating = false;
		}, 
		//this comes from the custom easing plugin
		easing: 'easeInOutBack'
	});
});

$(".submit").click(function(){
	return false;
})
</script>
{% endblock %}
{% endblock %}